import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { AtmaNormalFont, Doctor_GlitchFont } from "@/fonts/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${AtmaNormalFont.className} antialiased`}
      >
        <header 
          className="fixed top-0 left-0 right-0 p-8 flex items-center justify-center z-20"
          style={{
            background: "linear-gradient(to bottom, rgba(0,0,0) 0%, rgba(0,0,0,0.7) 40%, rgba(0,0,0,0.3) 90%, transparent 100%)"
          }}
        >
          <nav className='hidden md:flex items-center justify-center gap-4 text-xl'>
            <a href="#">Início</a>
            <a href="#">Cores</a>
            <a href="#">Sobre</a>
            <a href="#">Contato</a>
          </nav>

        </header>
        {children}
      </body>
    </html>
  );
}
